apiVersion: v1
kind: Service
metadata:
  name: service-go-app
  namespace: default
spec:
  selector:
    app: deployment-go-app
  type: NodePort
  ports:
  - name: service-go-app
    protocol: TCP
    port: 3000
    targetPort: 3000  
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    nodePort: 30010